# Railway configuration for Next.js deployment
# https://docs.railway.app/deploy/config-as-code

# [build] section removed to allow Railway auto-detection (Railpack/Nixpacks)
# Railpack automatically injects NEXT_PUBLIC_* environment variables at build time
# Uses standard Next.js build (not standalone) with default "next start" command

[deploy]
# startCommand removed - using Railway's default "next start" for standard builds
# Railpack handles the build and properly injects environment variables
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
